import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, { useRef, useState } from 'react'
import * as THREE from 'three'


const scene = new THREE.Scene();
// const camera = new THREE.PerspectiveCamera(75,window.innerWidth / window.innerHeight, 0.1, 1000 );
// const renderer = new THREE.WebGLRenderer();
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='w-full h-full absolute flex items-center justify-center'>
          <h1>EmbotrapIII</h1>
        </div>
        {children}
        <footer>--Created by OmooLab--</footer>
      </body>

    </html>
  )
}
